apiVersion: apps/v1
kind:
metadata:
  name: conversao-distancia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
      - name: conversao-distancia
        image: carlossantosdf/conversao-distancia:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia
spec:
  selector:
    app: conversao-distancia
  ports:
    - port: 80
      targetPort: 5000
      type: NodePort
      